name: docker
on:
  push:
    tags: [ "*.*.*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: docker/login-action@v2
      with:
        username: neowu
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64,linux/arm64/v8
        context: "kafka"
        tags: "neowu/kafka:${{ env.TAG }}"
        push: true
